
//   // Define constants for facet types
  const FACET_TYPES = {
    PRODUCT_TYPE: 'productType',
    CONSTRUCTION: 'construction',
    COLORS:'colors',
    SIZE: 'size',
    PRICE:'price',
    DENSITY:'density',
    BACKING:'backings',
    FIBER_TYPE: 'fiberType',
    DYE_METHOD: 'dyeMethod',
    FACEWEIGHT:'faceWeight',
    GAUGE: 'gauge',
    INSTALLATION:'installation',
    TOTALTHICKNESS: 'totalThickness',
    STYLE_NAME:'styleName',
    PATTERNS:'patternType',
    OVERALLTHICKNESS:'overallThickness',
    WOODSPECIES: 'woodSpecies',
    SURFACE_FINISH: 'surfaceFinish',
    WEARLAYER:'wearLayer'
  };
  
//   // Define the product structure
export const PRODUCTS_LIST = {
    ['SOFT_SURFACE']: [
      {
        type: 'Broadloom',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS,  FACET_TYPES.SIZE, FACET_TYPES.PRICE, FACET_TYPES.PATTERNS,FACET_TYPES.SIZE,
          FACET_TYPES.DENSITY,FACET_TYPES.BACKING, FACET_TYPES.FIBER_TYPE,FACET_TYPES.DYE_METHOD, FACET_TYPES.FACEWEIGHT,FACET_TYPES.TOTALTHICKNESS],
      },
      {
        type: 'Carpet Tile',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS,  FACET_TYPES.PATTERNS, FACET_TYPES.PRICE, FACET_TYPES.DENSITY,
          FACET_TYPES.BACKING, FACET_TYPES.FIBER_TYPE,FACET_TYPES.DYE_METHOD, FACET_TYPES.FACEWEIGHT,FACET_TYPES.TOTALTHICKNESS],
      },
      {
        type: 'View All Soft Surface',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS,  FACET_TYPES.SIZE, FACET_TYPES.PRICE, FACET_TYPES.DENSITY,
         FACET_TYPES.BACKING, FACET_TYPES.FIBER_TYPE,FACET_TYPES.DYE_METHOD, FACET_TYPES.FACEWEIGHT,],
      },
    ],
    ['HARD_SURFACE']: [
      {
        type: 'Luxury Vinyl Tile (LVT)',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.INSTALLATION,  FACET_TYPES.PRICE,
         FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE, FACET_TYPES.WEARLAYER,FACET_TYPES.SURFACE_FINISH],
      },
      {
        type: 'Resilient Sheet',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE,
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE, FACET_TYPES.WEARLAYER,FACET_TYPES.SURFACE_FINISH],
      },
      {
        type: 'Rubber',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE,
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE,FACET_TYPES.SURFACE_FINISH],
      },
      {
        type: 'Wood',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE, FACET_TYPES.WOODSPECIES,
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE,FACET_TYPES.SURFACE_FINISH,FACET_TYPES.INSTALLATION],
      },
      {
        type: 'Laminate',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE, 
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE,FACET_TYPES.SURFACE_FINISH,FACET_TYPES.INSTALLATION],
      },
      {
        type: 'Non-Vinyl Resilient',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE, FACET_TYPES.WEARLAYER,
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE,FACET_TYPES.SURFACE_FINISH,FACET_TYPES.INSTALLATION],
      },
      {
        type: 'HVT',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE, 
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE,FACET_TYPES.SURFACE_FINISH],
      },
      {
        type: 'HOMOGENEOUS_RESILIENT_TILE',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS, FACET_TYPES.PRICE, 
          FACET_TYPES.OVERALLTHICKNESS,FACET_TYPES.SIZE,FACET_TYPES.SURFACE_FINISH],
      },
      {
        type: 'View All Hard Surface',
        facets: [FACET_TYPES.CONSTRUCTION, FACET_TYPES.COLORS,FACET_TYPES.WEARLAYER, FACET_TYPES.PRICE, FACET_TYPES.OVERALLTHICKNESS,  FACET_TYPES.SIZE, FACET_TYPES.INSTALLATION,
         FACET_TYPES.WOODSPECIES, FACET_TYPES.SURFACE_FINISH],
      },
    ],
    ['ACCESSORIES']: [
      {
        type: 'Stair Tread',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.SIZE,  FACET_TYPES.TOTALTHICKNESS,
         FACET_TYPES.COLORS],
      },
      {
        type: 'Wall Base',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.SIZE,  FACET_TYPES.TOTALTHICKNESS,
         FACET_TYPES.COLORS],
      },
      {
        type: 'Trim And Transition',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.SIZE,  FACET_TYPES.TOTALTHICKNESS,
         FACET_TYPES.COLORS],
      },
      {
        type: 'Cushion/Pad',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.SIZE,  FACET_TYPES.TOTALTHICKNESS],
      },
      {
        type: 'Adhesives and Sundries',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.SIZE],
      },
      {
        type: 'Underlayment',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.SIZE],
      },
      {
        type: 'View All Accessories',
        facets: [FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.CONSTRUCTION, FACET_TYPES.SIZE, FACET_TYPES.TOTALTHICKNESS,
         FACET_TYPES.COLORS ],
      },
    ],
   
  };
