
//   // Define constants for facet types
  const FACET_TYPES = {
    BRAND: 'brand',
    PRODUCT_LINE: 'productLine',
    COLOR_FAMILY: 'colorFamily',
    STYLE_NAME:'styleName',
    PRODUCT_CATEGORY: 'displayProductCategory',
    CONSTRUCTION: 'construction',
    FIBER_TYPE: 'fiberType',
    ROLL_WIDTH: 'rollWidth',
    SIZE: 'size',
    TYPE: 'type',
    DYE_METHOD: 'dyeMethod',
    GAUGE: 'gauge',
    THICKNESS: 'thickness',
    FUTURE_DROP: 'futureDrop',
    MOISTURE_BARRIER: 'moistureBarrier',
    SPECIES: 'species',
    SURFACE_FINISH_VISUAL: 'surfaceFinish',
    PRODUCT_TYPE: 'productType',
    TIME_FRAME:'timeFrame'
  };
  
//   // Define the product structure
export const PRODUCTS_LIST = {
    ['SOFT_SURFACE']: [
      {
        type: 'Residential Broadloom',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.FIBER_TYPE, FACET_TYPES.ROLL_WIDTH, FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.THICKNESS, FACET_TYPES.FUTURE_DROP,FACET_TYPES.DYE_METHOD, FACET_TYPES.GAUGE,],
      },
      {
        type: 'Commercial Broadloom',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.FIBER_TYPE, FACET_TYPES.ROLL_WIDTH,  FACET_TYPES.CONSTRUCTION
            ,FACET_TYPES.DYE_METHOD, FACET_TYPES.GAUGE,FACET_TYPES.THICKNESS,FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Carpet Tile',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.FIBER_TYPE, FACET_TYPES.SIZE,  FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.THICKNESS,FACET_TYPES.DYE_METHOD, FACET_TYPES.GAUGE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Adhesives',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE, FACET_TYPES.TYPE,
         FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Pad & Cushion',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.CONSTRUCTION
        , FACET_TYPES.MOISTURE_BARRIER, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'View All Soft Surface',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE, FACET_TYPES.FIBER_TYPE, FACET_TYPES.ROLL_WIDTH,FACET_TYPES.TYPE, FACET_TYPES.CONSTRUCTION,
          FACET_TYPES.DYE_METHOD, FACET_TYPES.GAUGE, FACET_TYPES.THICKNESS, FACET_TYPES.MOISTURE_BARRIER, FACET_TYPES.FUTURE_DROP],
      },
    ],
    ['HARD_SURFACE']: [
      {
        type: 'Wood & Laminate',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.FUTURE_DROP,FACET_TYPES.SPECIES, FACET_TYPES.SURFACE_FINISH_VISUAL,],
      },
      {
        type: 'Resilient Vinyl',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.FUTURE_DROP,FACET_TYPES.SPECIES, FACET_TYPES.SURFACE_FINISH_VISUAL,],
      },
      {
        type: 'Underlayment',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Adhesives',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE, FACET_TYPES.TYPE, 
            FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Care & Maintenance',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'View All Hard Surface',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE,  FACET_TYPES.TYPE, FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.SPECIES, FACET_TYPES.SURFACE_FINISH_VISUAL,FACET_TYPES.FUTURE_DROP],
      },
    ],
    ['TILE']: [
      {
        type: 'Ceramic',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE, FACET_TYPES.CONSTRUCTION,
          FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Mosaics',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE, FACET_TYPES.CONSTRUCTION,
          FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Porcelain',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE,  FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Natural Stone',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE,  FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Decorative Accessories',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE,  FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Trim and Accents',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE,  FACET_TYPES.CONSTRUCTION,
        FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Setting Material',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE,  FACET_TYPES.CONSTRUCTION, 
            FACET_TYPES.FUTURE_DROP,FACET_TYPES.PRODUCT_TYPE,],
      },
      {
        type: 'View All Tile',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE, FACET_TYPES.CONSTRUCTION, 
             FACET_TYPES.PRODUCT_TYPE,,FACET_TYPES.FUTURE_DROP],
      },
    ],
    ['INDOOROUTDOOR']: [
      {
        type: 'Needlepunch Broadloom',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.ROLL_WIDTH, FACET_TYPES.CONSTRUCTION, 
             FACET_TYPES.GAUGE,FACET_TYPES.THICKNESS,FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Needlepunch Tile',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.SIZE, FACET_TYPES.CONSTRUCTION, 
         FACET_TYPES.GAUGE, FACET_TYPES.THICKNESS,FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Indoor/Outdoor',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.SIZE, FACET_TYPES.ROLL_WIDTH, FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.GAUGE, FACET_TYPES.THICKNESS,FACET_TYPES.FUTURE_DROP],
      },
    ],
    ['ACCESSORIES']: [
      {
        type: 'Trim and Moldings',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.PRODUCT_TYPE,FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Installation Kits & Tools',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY, FACET_TYPES.CONSTRUCTION,
             FACET_TYPES.PRODUCT_TYPE, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Wall Base & Stair Solutions',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.FUTURE_DROP,FACET_TYPES.PRODUCT_TYPE,],
      },
       {
        type: 'Powders',
        facets: [FACET_TYPES.BRAND],
      },
       {
        type: 'Tools',
        facets: [FACET_TYPES.BRAND],
      },
      {
        type: 'View All Accessories',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.COLOR_FAMILY,  FACET_TYPES.CONSTRUCTION,
         FACET_TYPES.FUTURE_DROP,FACET_TYPES.PRODUCT_TYPE, ],
      },
    ],
    ['MERCHANDISING']: [
      {
        type: 'Display',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE,  FACET_TYPES.TYPE
        , FACET_TYPES.TIME_FRAME,FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Display Updates',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE,  FACET_TYPES.TYPE,
        FACET_TYPES.TIME_FRAME, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'Graphics and Stickers',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE,  FACET_TYPES.TYPE, 
            FACET_TYPES.FUTURE_DROP,FACET_TYPES.TIME_FRAME,],
      },
      {
        type: 'Sales Tools',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE,  FACET_TYPES.TYPE,
        FACET_TYPES.TIME_FRAME,, FACET_TYPES.FUTURE_DROP],
      },
      {
        type: 'View All Merchandising',
        facets: [FACET_TYPES.BRAND, FACET_TYPES.PRODUCT_LINE, FACET_TYPES.SIZE,  FACET_TYPES.TYPE,
        FACET_TYPES.TIME_FRAME, FACET_TYPES.FUTURE_DROP],
      },
    ],
  };
