export const header = {
  Broadloom: {
    style: "Style#",
    styleName: "Style Name",
    width: "Width",
    fiber: "Fiber",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    category: "Collection",
    brand: "Brand",
    size: "Size",
    backing: "Backing",
    weightCarton: "Weight (Oz.)",
    patternRepeat: "Pattern Repeat",
    startDate: "Start Date",
    endDate: "End Date",
    rollPriceSY: "Roll Price (Sq. Yd.)",
    cutPriceSY: "Cut Price (Sq. Yd.)",
    rollPriceSF: "Roll Price (Sq. Ft.)",
    cutPriceSF: "Cut Price (Sq. Ft.)",
  },
  // 'Pattern Repeat':'Pattern Repeat',
  Cushion: {
    style: "Style#",
    styleName: "Style Name",
    // backing: "Backing",
    density: "Density",
    thickness: "Thickness",
    SYPerRoll: "SY/Roll",
    // // size: "Size",
    productCategory: "Product Category",
    collection: "Collection",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    brand: "Brand",
    startDate: "Start Date",
    endDate: "End Date",
    jobPackPriceSY: "Job Pack (< 25 rolls) Price (Sq. Yd.) ",
    warehousePriceSY: "Warehouse (25-49 rolls) Price (Sq. Yd.)",
    plantDirectPriceSY: "Plant Direct (50+ rolls) Price (Sq. Yd.)",
    rollSize: "Roll Size",
    category: "Category",
    moistureBarrier: "Moisture Barrier",
  },
  //'Density':'Density', 'Moisture Barrier':'Moisture Barrier', 'Thickness':'Thickness',  'Roll Size':'Roll Size','SY/Roll':'SY/Roll',  category:'Category',
  CarpetTile: {
    style: "Style#",
    styleName: "Style Name",
    productCategory: "Product Category",
    fiber: "Fiber",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    category: "Collection",
    brand: "Brand",
    backing: "Backing",
    size: "Size",
    SYPerCarton: "SY/Carton",
    cartonsPerPallet: "Cartons /Pallet",
    weightCarton: "Weight (Oz.)",
    startDate: "Start Date",
    endDate: "End Date",
    palletPriceSY: "Pallet Price (Sq. Yd.)",
    cartonPriceSY: "Carton Price (Sq. Yd.)",
    palletPriceSF: "Pallet Price (Sq. Ft.)",
    cartonPriceSF: "Carton Price (Sq. Ft.)",
  },
  ResilientSheet: {
    style: "Style#",
    styleName: "Style Name",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    category: "Collection",
    brand: "Brand",
    width: "Width",
    size: "Size",
    backing: "Backing",
    guage: "Gauge(Thickness)",
    startDate: "Start Date",
    endDate: "End Date",
    rollPriceSY: "Roll Price (Sq. Yd.)",
    cutPriceSY: "Cut Price (Sq. Yd.)",
    rollPriceSF: "Roll Price (Sq. Ft.)",
    cutPriceSF: "Cut Price (Sq. Ft.)",
  },
  //             //'Gauge':'Gauge',
  ResilientLVT: {
    style: "Style#",
    styleName: "Style Name",
    backing: "Backing",
    size: "Size",
    thickness: "Thickness",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    category: "Collection",
    brand: "Brand",
    // width: "Width", //Width x Length
    SFPerCarton: "SF/Carton",
    cartonsPerPallet: "Cartons /Pallet",
    startDate: "Start Date",
    endDate: "End Date",
    palletPriceSF: "Pallet Price (Sq. Ft.)",
    cartonPriceSF: "Carton Price (Sq. Ft.)",
  },
  //        'Thickness':'Thickness',
  Wood: {
    style: "Style#",
    styleName: "Style Name",
    // backing: "Backing",
    size: "Size",
    thickness: "Thickness",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    category: "Collection",
    brand: "Brand",
    // width: "Width", //Width x Length
    SFPerCarton: "SF/Carton",
    cartonsPerPallet: "Cartons /Pallet",
    startDate: "Start Date",
    endDate: "End Date",
    palletPriceSF: "Pallet Price (Sq. Ft.)",
    cartonPriceSF: "Carton Price (Sq. Ft.)",
  },
  //'Thickness':'Thickness',
  CeramicTile: {
    style: "Style#",
    styleName: "Style Name",
    // backing: "Backing",
    application: "Application",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    collection: "Collection",
    category: "Category",
    brand: "Brand",
    size: "Size",
    SFPerCarton: "SF/Carton",
    cartonsPerPallet: "Cartons /Pallet",
    weightCarton: "Weight /Carton",
    startDate: "Start Date",
    endDate: "End Date",
    palletPriceSF: "Pallet Price (Sq. Ft.)",
    cartonPriceSF: "Carton Price (Sq. Ft.)",
  },
  //'Application':'Application', category:'Category',
  Adhesives: {
    style: "Style#",
    styleName: "Style Name",
    partNumber: "Part#",
    spreadRate: "Spread Rate",
    // brand: "Brand",
    productCategory: "Product Category",
    productClass: "Product Class",
    salesChannel: "Sales Channel",
    brand: "Brand",
    category: "Collection",
    size: "Size",
    pailsPerPallet: "Pails /Pallet",
    uom: "UOM",
    startDate: "Start Date",
    endDate: "End Date",
    priceEach: "Price Each",
    pricePerEaPallet: "Price / EA Pallet",
  },
  // 'Price/ EA Pallet' :'Price/ EA Pallet ', 'Part #':'Part #', 'Spread Rate':'Spread Rate',
  Trims: {
    style: "Style#",
    styleName: "Style Name",
    partNumber: "Part#",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    productClass: "Product Line",
    category: "Collection",
    brand: "Brand",
    width: "Width",
    length: "Length",
    cartonsPerPallet: "Cartons /Pallet",
    uom: "UOM",
    startDate: "Start Date",
    endDate: "End Date",
    priceEach: "Price Each",
  },
  //'Part #':'Part #', 'Length':'Length',
  Accessories: {
    style: "Style#",
    styleName: "Style Name",
    // partNumber: "Part#",
    productCategory: "Product Category",
    productClass: "Product Class",
    brand: "Brand",
    salesChannel: "Sales Channel",
    // productClass: "Product Line",
    size: "Size",
    category: "Collection",
    uom: "UOM",
    startDate: "Start Date",
    endDate: "End Date",
    priceEach: "Price Each",
  },
  Underlayment: {
    style: "Style#",
    styleName: "Style Name",
    partNumber: "Part#",
    brand: "Brand",
    productCategory: "Product Category",
    salesChannel: "Sales Channel",
    thickness: "Thickness",
    // //brand: "Brand",
    SFPerUnit: "SF/Unit",
    unitsPerPallet: "Units /Pallet",
    size: "Size",
    uom: "UOM",
    startDate: "Start Date",
    endDate: "End Date",
    palletPriceSF: "Pallet Price (Sq. Ft.)",
    priceEach: "Price Each",
  },
  //                  //'Part #':'Part #','Thickness':'Thickness', 'SF/Unit':'SF/Unit', 'Units/Pallet':'Units/Pallet',
};
export const columnHeader = {
  Broadloom: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "rollPriceSY",
      title: "Roll Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cutPriceSY",
      title: "Cut Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "rollPriceSF",
      title: "Roll Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cutPriceSF",
      title: "Cut Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  Cushion: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "density",
      title: "Density",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "thickness",
      title: "Thickness",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "SYPerRoll",
      title: "SY/Roll",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "jobPackPriceSY",
      title: "Job Pack (< 25 rolls) Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "warehousePriceSY",
      title: "Warehouse (25-49 rolls) Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "plantDirectPriceSY",
      title: "Plant Direct (50+ rolls) Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  CarpetTile: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "SYPerCarton",
      title: "SY/Carton",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonsPerPallet",
      title: "Cartons /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "palletPriceSY",
      title: "Pallet Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonPriceSY",
      title: "Carton Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "palletPriceSF",
      title: "Pallet Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonPriceSF",
      title: "Carton Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  ResilientSheet: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "guage",
      title: "Gauge(Thickness)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "rollPriceSY",
      title: "Roll Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cutPriceSY",
      title: "Cut Price (Sq. Yd.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "rollPriceSF",
      title: "Roll Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cutPriceSF",
      title: "Cut Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  ResilientLVT: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "thickness",
      title: "Thickness",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "SFPerCarton",
      title: "SF/Carton",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonsPerPallet",
      title: "Cartons /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "palletPriceSF",
      title: "Pallet Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonPriceSF",
      title: "Carton Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  Wood: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "thickness",
      title: "Thickness",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "SFPerCarton",
      title: "SF/Carton",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonsPerPallet",
      title: "Cartons /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "palletPriceSF",
      title: "Pallet Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonPriceSF",
      title: "Carton Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  CeramicTile: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "backing",
      title: "Backing",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "application",
      title: "Application",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "SFPerCarton",
      title: "SF/Carton",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonsPerPallet",
      title: "Cartons /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "weightCarton",
      title: "Weight /Carton",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "palletPriceSF",
      title: "Pallet Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonPriceSF",
      title: "Carton Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  Adhesives: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "partNumber",
      title: "Part#",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "brand",
      title: "Brand",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "spreadRate",
      title: "Spread Rate",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "size",
      title: "Size",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "pailsPerPallet",
      title: "Pails /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "uom",
      title: "UOM",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "priceEach",
      title: "Price Each",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "pricePerEaPallet",
      title: "Price / EA Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  Trims: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "productCategory",
      title: "Product Category",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "brand",
      title: "Brand",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "width",
      title: "Width",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "length",
      title: "Length",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "cartonsPerPallet",
      title: "Cartons /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "uom",
      title: "UOM",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "priceEach",
      title: "Price Each",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  Accessories: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "partNumber",
      title: "Part#",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "productCategory",
      title: "Product Category",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "brand",
      title: "Brand",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "uom",
      title: "UOM",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "priceEach",
      title: "Price Each",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
  Underlayment: [
    {
      key: "style",
      title: "Style #",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "styleName",
      title: "Style Name",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "brand",
      title: "Brand",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "SFPerUnit",
      title: "SF/Unit",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "unitsPerPallet",
      title: "Units /Pallet",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "uom",
      title: "UOM",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "startDate",
      title: "Start Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "endDate",
      title: "End Date",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "palletPriceSF",
      title: "Pallet Price (Sq. Ft.)",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
    {
      key: "priceEach",
      title: "Price Each",
      cssClass: { includeHeader: true, name: "sorting-arrow" },
    },
  ],
};
